[package]
name = "museum"
version = "0.1.0"
edition = "2021"


[dependencies]
bevy = { version = "0.7", default-features = false, features = ["bevy_winit", "render", "png", "bevy_audio", "x11"]}
smooth-bevy-cameras = "0.4"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
